### ISSUE TITLE
Presented this error when running in termux.

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Sorrow446/MOOV-DL#3] opened 2021-01-18 13:49 UTC
README.md  config.json  moov-dl.py   requirements.txt
api        ffmpeg       moov-dl_tmp
$ python moov-dl.py -u https://moov.hk/#/album/VASB00280151A

 _____ _____ _____ _____     ____  __
|     |     |     |  |  |___|    \|  |
| | | |  |  |  |  |  |  |___|  |  |  |__
|_|_|_|_____|_____|\___/    |____/|_____|

Signed in successfully.

Album 1 of 1:
Europe - Definitive Collection
Unavailable in "HR". "LL" will be used instead.
Downloading track 1 of 18: The Final Countdown - 16-bit / 44.1 kHz FLAC
100%|██████████████████████████78/78 segments [12:04<00:00]
Failed to rip track.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/mutagen/_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/storage/music/Europe - Definitive Collection/1.flac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by Sorrow446** [comment] 2021-01-18 22:56
Dupe of https://github.com/Sorrow446/MOOV-DL/issues/1. Seems to be a Linux-only issue. The path (pre_path) is used before the tagging with no problems here: 
```python
download(file_meta, parsed_meta, pre_path)
```
But the tagging fails with the exact same path.
```python
write_tags(pre_path, parsed_meta, cov_path)
```

Will look into this. Is your `output_dir` option set to default?

**Comment by Sorrow446** [comment] 2021-01-19 00:36
Pushed fix. Please try it.

**Comment by adrianmejiam** [comment] 2021-01-19 15:20
Working perfectly .. thanks

**Closed** 2021-01-19 22:52 UTC

**Comment by WellingtonMonteiro** [comment] 2021-01-19 22:55
Obrigado pela atenção.
